name: 01-building-blocks-1

on: push

jobs:
    job1: 
        runs-on: ubuntu-latest
        steps:
            - name: first job
              run: echo "Hello World Angshuman"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: second job
              run: echo "Hello Family"
              

        