name: 02 - Workflow Events
on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: 

    job1: 
        runs-on: ubuntu-latest
        steps:
            - name: first job
              run: echo "Hello World Angshuman"

